if(NOT DEFINED GLFW_X11_SOURCE OR NOT DEFINED GLFW_X11_OUTPUT)
    message(FATAL_ERROR "GLFW_X11_SOURCE and GLFW_X11_OUTPUT are required")
endif()
if(NOT EXISTS "${GLFW_X11_SOURCE}")
    message(FATAL_ERROR "GLFW X11 source not found: ${GLFW_X11_SOURCE}")
endif()

set(expected_source_hash "617C5088F6C70B8A9DE0FA83538F93D749368AAF3C379FCC331B928C3353F370")
set(expected_output_hash "8CE625AA965D6DA401CE3F4992FDB53AC4ECD34BC00B22BBAEFFAB41F72B0DAE")
get_filename_component(output_directory "${GLFW_X11_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
file(READ "${GLFW_X11_SOURCE}" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(SHA256 source_hash "${source}")
string(TOUPPER "${source_hash}" source_hash)

if(source_hash STREQUAL expected_output_hash OR source_hash STREQUAL "A4B7E67319996FC50B3BC0AE6943E6141A0B6B400E3C4F3F7279979DAFD02258")
    configure_file("${GLFW_X11_SOURCE}" "${GLFW_X11_OUTPUT}" COPYONLY)
    return()
endif()
if(NOT source_hash STREQUAL expected_source_hash)
    message(FATAL_ERROR
        "Unsupported GLFW X11 source hash ${source_hash}; expected pristine GLFW 3.4 "
        "${expected_source_hash} or patched ${expected_output_hash}. Review and update "
        "scripts/patch_glfw_x11_ime.cmake for this GLFW revision.")
endif()

file(READ "${GLFW_X11_SOURCE}" source)
set(key_press_before "        case KeyPress:\n        {\n            const int key = translateKey(keycode);")
set(key_press_after "        case KeyPress:\n        {\n            if (filtered)\n                return;\n\n            const int key = translateKey(keycode);")
set(key_release_before "        case KeyRelease:\n        {\n            const int key = translateKey(keycode);")
set(key_release_after "        case KeyRelease:\n        {\n            if (filtered)\n                return;\n\n            const int key = translateKey(keycode);")
string(FIND "${source}" "${key_press_before}" key_press_offset)
string(FIND "${source}" "${key_release_before}" key_release_offset)
if(key_press_offset EQUAL -1 OR key_release_offset EQUAL -1)
    message(FATAL_ERROR "GLFW X11 key dispatch blocks do not match the reviewed patch context")
endif()
string(REPLACE "${key_press_before}" "${key_press_after}" source "${source}")
string(REPLACE "${key_release_before}" "${key_release_after}" source "${source}")

file(WRITE "${GLFW_X11_OUTPUT}" "${source}")
string(SHA256 output_hash "${source}")
string(TOUPPER "${output_hash}" output_hash)
if(NOT output_hash STREQUAL expected_output_hash)
    file(REMOVE "${GLFW_X11_OUTPUT}")
    message(FATAL_ERROR "Patched GLFW X11 source hash mismatch: ${output_hash}")
endif()
