if(NOT DEFINED GLFW_X11_SOURCE OR NOT DEFINED GLFW_X11_OUTPUT)
    message(FATAL_ERROR "GLFW_X11_SOURCE and GLFW_X11_OUTPUT are required")
endif()
if(NOT EXISTS "${GLFW_X11_SOURCE}")
    message(FATAL_ERROR "GLFW X11 source not found: ${GLFW_X11_SOURCE}")
endif()

set(expected_source_hash "7C5A60A507767C5B311437A74E85E547914DF631BE4F74FA75746063762019DA")
set(expected_output_hash "B1B9E54E20A687EC45E869D0D0E942220D68F087BF0727CB2091C7E9BF56ED12")
get_filename_component(output_directory "${GLFW_X11_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
file(SHA256 "${GLFW_X11_SOURCE}" source_hash)
string(TOUPPER "${source_hash}" source_hash)

if(source_hash STREQUAL expected_output_hash)
    configure_file("${GLFW_X11_SOURCE}" "${GLFW_X11_OUTPUT}" COPYONLY)
    return()
endif()
if(NOT source_hash STREQUAL expected_source_hash)
    message(FATAL_ERROR
        "Unsupported GLFW X11 source hash ${source_hash}; expected pristine GLFW 3.4 "
        "${expected_source_hash} or patched ${expected_output_hash}. Review and update "
        "scripts/patch_glfw_x11_ime.cmake for this GLFW revision.")
endif()

file(READ "${GLFW_X11_SOURCE}" source)
set(key_press_before "        case KeyPress:\n        {\n            const int key = translateKey(keycode);")
set(key_press_after "        case KeyPress:\n        {\n            if (filtered)\n                return;\n\n            const int key = translateKey(keycode);")
set(key_release_before "        case KeyRelease:\n        {\n            const int key = translateKey(keycode);")
set(key_release_after "        case KeyRelease:\n        {\n            if (filtered)\n                return;\n\n            const int key = translateKey(keycode);")
string(FIND "${source}" "${key_press_before}" key_press_offset)
string(FIND "${source}" "${key_release_before}" key_release_offset)
if(key_press_offset EQUAL -1 OR key_release_offset EQUAL -1)
    message(FATAL_ERROR "GLFW X11 key dispatch blocks do not match the reviewed patch context")
endif()
string(REPLACE "${key_press_before}" "${key_press_after}" source "${source}")
string(REPLACE "${key_release_before}" "${key_release_after}" source "${source}")

file(WRITE "${GLFW_X11_OUTPUT}" "${source}")
file(SHA256 "${GLFW_X11_OUTPUT}" output_hash)
string(TOUPPER "${output_hash}" output_hash)
if(NOT output_hash STREQUAL expected_output_hash)
    file(REMOVE "${GLFW_X11_OUTPUT}")
    message(FATAL_ERROR "Patched GLFW X11 source hash mismatch: ${output_hash}")
endif()
