if(TARGET ZLIB::ZLIB)
    set(ZLIB_FOUND TRUE)
    set(ZLIB_LIBRARIES ZLIB::ZLIB)
    set(ZLIB_LIBRARY ZLIB::ZLIB)
    get_target_property(ZLIB_INCLUDE_DIRS ZLIB::ZLIB INTERFACE_INCLUDE_DIRECTORIES)
    if(NOT ZLIB_INCLUDE_DIRS)
        set(ZLIB_INCLUDE_DIRS "")
    endif()
    set(ZLIB_INCLUDE_DIR "${ZLIB_INCLUDE_DIRS}")
else()
    include("${CMAKE_ROOT}/Modules/FindZLIB.cmake")
endif()
